name: video_player_android
description: Android implementation of the video_player plugin.
repository: https://github.com/flutter/packages/tree/main/packages/video_player/video_player_android
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+video_player%22
version: 2.4.9

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

flutter:
  plugin:
    implements: video_player
    platforms:
      android:
        dartPluginClass: AndroidVideoPlayer
        package: io.flutter.plugins.videoplayer
        pluginClass: VideoPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
  # video_player_platform_interface: ">=6.1.0 <7.0.0"
  #video_player_platform_interface:
  #  path: ../video_player_platform_interface
  video_player_platform_interface:
    git:
      url: https://github.com/Mto292/packages.git
      path: packages/video_player/video_player_platform_interface
      ref: c27a98aa5b8671c3589a80bdd3d7918d292a57a7

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^9.2.5
